package com.imesmuaran.alternatetechnics.client.models;

// Date: 05.07.2014 17:31:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBucket extends ModelBase {
    //fields
   public ModelRenderer Shape2;
   public ModelRenderer Shape1;
   public ModelRenderer Shape3;
   public ModelRenderer Shape5;
   public ModelRenderer Shape6;
   public ModelRenderer Shape7;
   public ModelRenderer Shape8;

    public ModelBucket() {
        this.textureWidth = 64;
        this.textureHeight = 32;

        this.Shape1 = new ModelRenderer(this, 0, -12);
        this.Shape1.addBox(0F, 0F, 0F, 0, 14, 12);
        this.Shape1.setRotationPoint(-6F, 10F, -6F);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(Shape1, 0F, 0F, 0F);
        //this.Shape1.mirror = false;
        
        this.Shape2 = new ModelRenderer(this, -12, 0);
        this.Shape2.addBox(0F, 0F, 0F, 12, 14, 0);
        this.Shape2.setRotationPoint(-6F, 10F, -6F);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(Shape2, 0F, 0F, 0F);
        //this.Shape2.mirror = false;

        this.Shape2 = new ModelRenderer(this, 0, 0);
        this.Shape2.addBox(0F, -3F, 0F, 12, 14, 0);
        this.Shape2.setRotationPoint(-6F, 13F, 6F);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(Shape2, 0F, 0F, 0F);
        //this.Shape2.mirror = false;
        
        this.Shape1 = new ModelRenderer(this, 0, -12);
        this.Shape1.addBox(0F, 0F, 0F, 0, 14, 12);
        this.Shape1.setRotationPoint(6F, 10F, -6F);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(Shape1, 0F, 0F, 0F);
        
        this.Shape3 = new ModelRenderer(this, -12, 14);
        this.Shape3.addBox(0F, 0F, 0F, 12, 0, 12);
        this.Shape3.setRotationPoint(-6F, 24F, -6F);
        this.Shape3.setTextureSize(64, 32);
        this.Shape3.mirror = true;
        this.setRotation(Shape3, 0F, 0F, 0F);
        
        this.Shape5 = new ModelRenderer(this, 22, 14);
        this.Shape5.addBox(0F, 0F, 0F, 12, 0, 12);
        this.Shape5.setRotationPoint(-6F, 10F, -6F);
        this.Shape5.setTextureSize(64, 32);
        this.Shape5.mirror = true;
        this.setRotation(Shape5, 0F, 0F, 0F);
        
        this.Shape6 = new ModelRenderer(this, 4, 14);
        this.Shape6.addBox(0F, 0F, 0F, 10, 0, 10);
        this.Shape6.setRotationPoint(-5F, 23F, -5F);
        this.Shape6.setTextureSize(64, 32);
        this.Shape6.mirror = true;
        this.setRotation(Shape6, 0F, 0F, 0F);
        
        this.Shape7 = new ModelRenderer(this, 24, -9);
        this.Shape7.addBox(0F, 0F, 0F, 0, 13, 10);
        this.Shape7.setRotationPoint(-5F, 10F, -5F);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(Shape7, 0F, 0F, 0F);
        
        this.Shape7 = new ModelRenderer(this, 14, -9);
        this.Shape7.addBox(0F, 0F, 0F, 0, 13, 10);
        this.Shape7.setRotationPoint(5F, 10F, -5F);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(Shape7, 0F, 0F, 0F);
        
        this.Shape8 = new ModelRenderer(this, 24, 1);
        this.Shape8.addBox(0F, 0F, 0F, 10, 13, 0);
        this.Shape8.setRotationPoint(-5F, 10F, -5F);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(Shape8, 0F, 0F, 0F);
        
        this.Shape8 = new ModelRenderer(this, 14, 1);
        this.Shape8.addBox(0F, 0F, 0F, 10, 13, 0);
        this.Shape8.setRotationPoint(-5F, 10F, 5F);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(Shape8, 0F, 0F, 0F);
        
        // Original
        /*
        this.Shape1 = new ModelRenderer(this, 0, -12);
        this.Shape1.mirror = true;
        this.Shape1.addBox(0F, 0F, 0F, 0, 14, 12);
        this.Shape1.setRotationPoint(-6F, 10F, -6F);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(Shape1, 0F, 0F, 0F);
        this.Shape1.mirror = false;
        
        this.Shape2 = new ModelRenderer(this, -12, 0);
        this.Shape2.mirror = true;
        this.Shape2.addBox(0F, 0F, 0F, 12, 14, 0);
        this.Shape2.setRotationPoint(-6F, 10F, -6F);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(Shape2, 0F, 0F, 0F);
        this.Shape2.mirror = false;

        this.Shape2 = new ModelRenderer(this, 0, 0);
        this.Shape2.mirror = true;
        this.Shape2.addBox(0F, -3F, 0F, 12, 14, 0);
        this.Shape2.setRotationPoint(-6F, 13F, 6F);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(Shape2, 0F, 0F, 0F);
        this.Shape2.mirror = false;
        
        this.Shape1 = new ModelRenderer(this, 0, -12);
        this.Shape1.addBox(0F, 0F, 0F, 0, 14, 12);
        this.Shape1.setRotationPoint(6F, 10F, -6F);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(Shape1, 0F, 0F, 0F);
        
        this.Shape3 = new ModelRenderer(this, -12, 14);
        this.Shape3.addBox(0F, 0F, 0F, 12, 0, 12);
        this.Shape3.setRotationPoint(-6F, 24F, -6F);
        this.Shape3.setTextureSize(64, 32);
        this.Shape3.mirror = true;
        this.setRotation(Shape3, 0F, 0F, 0F);
        
        this.Shape5 = new ModelRenderer(this, 22, 14);
        this.Shape5.addBox(0F, 0F, 0F, 12, 0, 12);
        this.Shape5.setRotationPoint(-6F, 10F, -6F);
        this.Shape5.setTextureSize(64, 32);
        this.Shape5.mirror = true;
        this.setRotation(Shape5, 0F, 0F, 0F);
        
        this.Shape6 = new ModelRenderer(this, 4, 14);
        this.Shape6.addBox(0F, 0F, 0F, 10, 0, 10);
        this.Shape6.setRotationPoint(-5F, 23F, -5F);
        this.Shape6.setTextureSize(64, 32);
        this.Shape6.mirror = true;
        this.setRotation(Shape6, 0F, 0F, 0F);
        
        this.Shape7 = new ModelRenderer(this, 24, -9);
        this.Shape7.addBox(0F, 0F, 0F, 0, 13, 10);
        this.Shape7.setRotationPoint(-5F, 10F, -5F);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(Shape7, 0F, 0F, 0F);
        
        this.Shape7 = new ModelRenderer(this, 14, -9);
        this.Shape7.addBox(0F, 0F, 0F, 0, 13, 10);
        this.Shape7.setRotationPoint(5F, 10F, -5F);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(Shape7, 0F, 0F, 0F);
        
        this.Shape8 = new ModelRenderer(this, 24, 1);
        this.Shape8.addBox(0F, 0F, 0F, 10, 13, 0);
        this.Shape8.setRotationPoint(-5F, 10F, -5F);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(Shape8, 0F, 0F, 0F);
        
        this.Shape8 = new ModelRenderer(this, 14, 1);
        this.Shape8.addBox(0F, 0F, 0F, 10, 13, 0);
        this.Shape8.setRotationPoint(-5F, 10F, 5F);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(Shape8, 0F, 0F, 0F);
         */
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.Shape1.render(f5);
        this.Shape2.render(f5);
        //this.Shape2.render(f5);
        //this.Shape1.render(f5);
        this.Shape3.render(f5);
        this.Shape5.render(f5);
        this.Shape6.render(f5);
        this.Shape7.render(f5);
        //this.Shape7.render(f5);
        this.Shape8.render(f5);
        //this.Shape8.render(f5);
    }
    
    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
	/*
    public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }
    */
}

