package com.imesmuaran.alternatetechnics.client.models;

// Date: 05.07.2014 17:31:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBucket extends ModelBase {
    //fields
    ModelRenderer Shape2;
    ModelRenderer Shape1;
    ModelRenderer Shape3;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;

    public ModelBucket() {
        textureWidth = 64;
        textureHeight = 32;

        Shape1.mirror = true;
        Shape1 = new ModelRenderer(this, 0, -12);
        Shape1.addBox(0F, 0F, 0F, 0, 14, 12);
        Shape1.setRotationPoint(-6F, 10F, -6F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape1.mirror = false;
        Shape2.mirror = true;
        Shape2 = new ModelRenderer(this, -12, 0);
        Shape2.addBox(0F, 0F, 0F, 12, 14, 0);
        Shape2.setRotationPoint(-6F, 10F, -6F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape2.mirror = false;
        Shape2.mirror = true;
        Shape2 = new ModelRenderer(this, 0, 0);
        Shape2.addBox(0F, -3F, 0F, 12, 14, 0);
        Shape2.setRotationPoint(-6F, 13F, 6F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape2.mirror = false;
        Shape1 = new ModelRenderer(this, 0, -12);
        Shape1.addBox(0F, 0F, 0F, 0, 14, 12);
        Shape1.setRotationPoint(6F, 10F, -6F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, -12, 14);
        Shape3.addBox(0F, 0F, 0F, 12, 0, 12);
        Shape3.setRotationPoint(-6F, 24F, -6F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 22, 14);
        Shape5.addBox(0F, 0F, 0F, 12, 0, 12);
        Shape5.setRotationPoint(-6F, 10F, -6F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 4, 14);
        Shape6.addBox(0F, 0F, 0F, 10, 0, 10);
        Shape6.setRotationPoint(-5F, 23F, -5F);
        Shape6.setTextureSize(64, 32);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 24, -9);
        Shape7.addBox(0F, 0F, 0F, 0, 13, 10);
        Shape7.setRotationPoint(-5F, 10F, -5F);
        Shape7.setTextureSize(64, 32);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 14, -9);
        Shape7.addBox(0F, 0F, 0F, 0, 13, 10);
        Shape7.setRotationPoint(5F, 10F, -5F);
        Shape7.setTextureSize(64, 32);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 24, 1);
        Shape8.addBox(0F, 0F, 0F, 10, 13, 0);
        Shape8.setRotationPoint(-5F, 10F, -5F);
        Shape8.setTextureSize(64, 32);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 14, 1);
        Shape8.addBox(0F, 0F, 0F, 10, 13, 0);
        Shape8.setRotationPoint(-5F, 10F, 5F);
        Shape8.setTextureSize(64, 32);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(entity, f, f1, f2, f3, f4, f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape2.render(f5);
        Shape1.render(f5);
        Shape3.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape8.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}

